Fix inserts in translations table
lansuite/lansuite pull request #463
Opened 2021-01-03 15:14 UTC by t-h-e

see code change in modules/install/Classes/Install.php
Length of $org and other translations need to be checked for size
 restrictions (255 chars), as they may be longer than $org

also fixed UTF-8 encoding issues

fixes parts of #456

2021-01-10 11:15 UTC, andygrunwald commented on modules/tournament2/mod_settings/translation.xml
> +				<org>Neues Team (Spieler) anmeldenHTML_NEWLINE(Nur in Anmeldephase müglich)</org>
```suggestion
				<org>Neues Team (Spieler) anmeldenHTML_NEWLINE(Nur in Anmeldephase möglich)</org>

```

2021-01-10 11:18 UTC, andygrunwald requested changes
@t-h-e Thanks a lot.
In general, it looks pretty good. I left a small comment, before merging.

2021-03-04 15:23 UTC, M4LuZ commented
Requested change was done, thus OK and fine to merge

2021-03-04 15:24 UTC, M4LuZ approved these changes

2021-03-04 15:24 UTC, merged